### ISSUE TITLE
Bug/regression: no counter-example for `\xs -> nub xs == (xs :: [Int])`

### ISSUE THREAD

**Issue by rudymatela** [leepike/SmartCheck#10]
Hi,

I think I found a regression on SmartCheck-0.2.2 in relation to SmartCheck-0.2.1.

Consider the following minimal SmartChecking program:

```haskell
import Test.SmartCheck
import Data.List (nub)

main :: IO ()
main = smartCheck scStdArgs{format = PrintString}
     $ \xs -> nub xs == (xs :: [Int])
```

0.2.1
-----

When compiled and run against smartcheck-0.2.1, it produces:

```
$ ghc-7.10 -dynamic list.hs
$ yes | ./list
*** Finding a counterexample with QuickCheck...
*** Failed! Falsifiable (after 6 tests):  
*** Smart Shrinking ...
*** Smart-shrunk value:
[-2,-2]
*** Extrapolating values ...
*** Extrapolating Constructors ...
*** Extrapolated value:
forall values x0:
: -2 (: -2 x0)
*** Done.
```

So far so good.  This is what I would expect.  The tail of the list is generalized.  The property fails regardless of the tail.

(Above, I have trimmed/summarized the output a bit.)

0.2.2
-----

When compiled and run against smartcheck-0.2.2, it produces:

```
$ ghc-7.10 -dynamic list.hs
$ yes | list
*** Finding a counterexample with QuickCheck...
+++ OK, passed 1 tests.

*** Analyzing the first argument of the property with SmartCheck...
*** (If any stage takes too long, modify SmartCheck's arguments.)
*** No value to smart-shrink; done.
```

SmartCheck fails to report a counter-example and says it passes the property for just 1 test.

(Above, output is in full.)

Details
------

* smartcheck-0.2.1 was compiled against QuickCheck-2.7.6;
* smartcheck-0.2.2 was compiled against QuickCheck-2.9.2;
* In both cases I was using GHC 7.10.3;
* This is perhaps related to issue #5.

**Comment by rudymatela** [comment]
I further investigated into this.

It seems the problem is using SmartCheck-0.2.2 with QuickCheck-2.9.2.

If I compile SmartCheck-0.2.2 against QuickCheck-2.8.2 it produces the expected counter-example and its generalization:

```
$ yes | ./list 
*** Failed! Falsifiable (after 6 tests and 1 shrink):     
[0,0]
*** Finding a counterexample with QuickCheck...
*** Failed! Falsifiable (after 7 tests):  
*** Non SmartChecked arguments:

*** Analyzing the first argument of the property with SmartCheck...
*** (If any stage takes too long, modify SmartCheck's arguments.)

*** Smart Shrinking ...
*** Smart-shrunk value:
[4,-2,4]

*** Extrapolating values ...

*** Extrapolating Constructors ...

*** Extrapolated value:
forall values x0:

: 4 (: -2 (: 4 x0))


Attempt to find a new counterexample?
  ('Enter' to continue; any character then 'Enter' to quit.)
*** Done.
```

**Comment by leepike** [comment]
Thanks. As you reported in [https://github.com/leepike/SmartCheck/issues/10](Issue 10), QC has changed a lot, and I'm using it's guts. I'll try to track this down and fix it soon.

**Comment by leepike** [comment]
This also should be fixed (for now by pinning) as reported in Issue #9.
